name: ccl_doc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:

    sdk: flutter

  flutter_secure_storage: ^7.0.1
  camera: ^0.5.8
  google_sign_in: ^5.4.4
  http: ^0.13.5
  googleapis: ^10.0.0
  googleapis_auth: ^1.3.1
  confirm_dialog: ^1.0.1
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  draw_on_image_plugin: ^1.0.0
  splashscreen: ^1.3.5
  geolocator: ^9.0.2
  intl: ^0.18.0
  loading_animations: ^2.2.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
  - images/cclogo.png


